### ISSUE TITLE
No Visual/Audio Cue on shop purchase

### ISSUE THREAD

**Issue by Danicus2000000** [HeckingGoose/Dr-Coomer-Neopet#1]
Visual and/or audio cues could be present when purchasing (or failing to purchase) items from a shop even if this is a MessageBox or similar it would be better than no prompt

**Comment by Danicus2000000** [comment]
E.g. a cha ching noise when buying items  successfully or a du dur noise when unable to buy

**Comment by HeckingGoose** [comment]
Implemented as of [this](https://github.com/HeckingGoose/Dr-Coomer-Neopet/commit/100b9861630eb7ba8eee249de3bc805a0fda699f) commit.

Uses particles instead of sound effects.
