### ISSUE TITLE
Button Highlighting

### ISSUE THREAD

**Issue by Danicus2000000** [HeckingGoose/Dr-Coomer-Neopet#2]
Buttons in C# have an event within them for being hovered over this can be used to change the button colour for more visual Cues

**Comment by HeckingGoose** [comment]
Button highlighting already exists, it seems the shades that I was using were a bit too subtle. Fixed this issue [here](https://github.com/HeckingGoose/Dr-Coomer-Neopet/commit/1119d5a7605b380bb7752eb93f062394758f934c).
